var ERROR_CODES = {
  // 通用
  SUCCESS: 0,
  UNKNOWN: 1000,
  NETWORK_ERROR: 1001,

  // 认证 2xxx
  ERR_AUTH_FAILED: 2001,
  ERR_NOT_LOGIN: 2002,
  ERR_PERMISSION_DENIED: 2003,

  // 商品 3xxx
  ERR_GOODS_NOT_FOUND: 3001,
  ERR_GOODS_VALIDATION: 3002,
  ERR_GOODS_IMAGES_REQUIRED: 3003,
  ERR_GOODS_TITLE_REQUIRED: 3004,
  ERR_GOODS_PRICE_REQUIRED: 3005,
  ERR_GOODS_CATEGORY_REQUIRED: 3006,
  ERR_GOODS_CONDITION_REQUIRED: 3007,
  ERR_GOODS_DESC_REQUIRED: 3008,
  ERR_CONTENT_RISKY: 3100,
  ERR_IMAGE_RISKY: 3101,

  // 用户 4xxx
  ERR_USER_NOT_FOUND: 4001,

  // 消息 5xxx
  ERR_MESSAGE_EMPTY: 5001,
  ERR_MESSAGE_TARGET_MISSING: 5002,

  // 收藏 6xxx
  ERR_COLLECTION_GOODS_MISSING: 6001
};

var ERROR_MESSAGES = {};
ERROR_MESSAGES[ERROR_CODES.ERR_AUTH_FAILED] = '登录验证失败，请重新登录';
ERROR_MESSAGES[ERROR_CODES.ERR_NOT_LOGIN] = '请先登录';
ERROR_MESSAGES[ERROR_CODES.ERR_PERMISSION_DENIED] = '没有操作权限';
ERROR_MESSAGES[ERROR_CODES.ERR_GOODS_NOT_FOUND] = '商品不存在';
ERROR_MESSAGES[ERROR_CODES.ERR_GOODS_VALIDATION] = '商品信息不完整';
ERROR_MESSAGES[ERROR_CODES.ERR_GOODS_IMAGES_REQUIRED] = '请至少上传1张商品图片';
ERROR_MESSAGES[ERROR_CODES.ERR_GOODS_TITLE_REQUIRED] = '请输入商品标题';
ERROR_MESSAGES[ERROR_CODES.ERR_GOODS_PRICE_REQUIRED] = '请输入价格';
ERROR_MESSAGES[ERROR_CODES.ERR_GOODS_CATEGORY_REQUIRED] = '请选择商品分类';
ERROR_MESSAGES[ERROR_CODES.ERR_GOODS_CONDITION_REQUIRED] = '请选择商品成色';
ERROR_MESSAGES[ERROR_CODES.ERR_GOODS_DESC_REQUIRED] = '请输入商品描述';
ERROR_MESSAGES[ERROR_CODES.ERR_CONTENT_RISKY] = '商品信息包含违规内容，请修改后重试';
ERROR_MESSAGES[ERROR_CODES.ERR_IMAGE_RISKY] = '商品图片包含违规内容，请更换后重试';
ERROR_MESSAGES[ERROR_CODES.ERR_USER_NOT_FOUND] = '用户不存在';
ERROR_MESSAGES[ERROR_CODES.ERR_MESSAGE_EMPTY] = '消息内容不能为空';
ERROR_MESSAGES[ERROR_CODES.ERR_MESSAGE_TARGET_MISSING] = '缺少接收用户';
ERROR_MESSAGES[ERROR_CODES.ERR_COLLECTION_GOODS_MISSING] = '缺少商品ID';

function getErrorMessage(code) {
  return ERROR_MESSAGES[code] || '操作失败，请重试';
}

module.exports = {
  ERROR_CODES: ERROR_CODES,
  ERROR_MESSAGES: ERROR_MESSAGES,
  getErrorMessage: getErrorMessage
};
